### ISSUE TITLE
can't load the game with this mod installed

### ISSUE THREAD

**Issue by Apiterbakar** [TonimatasDEV/PotionTimeStacker#1]
[2022-12-16-3.log.gz](https://github.com/TonimatasDEV/PotionTimeStacker/files/10257892/2022-12-16-3.log.gz)
[Tiny.zip](https://github.com/TonimatasDEV/PotionTimeStacker/files/10257900/Tiny.zip)
and those are the log and the mod list

**Comment by wDona** [comment]
@TonimatasDEV

**Comment by TonimatasDEV** [comment]
Fixed in 1.0.1.

Download: https://modrinth.com/mod/potiontimestacker/versions

**Comment by Apiterbakar** [comment]
Thank you
