### ISSUE TITLE
[Suggestion] Configurable max effect duration and effect blacklist

### ISSUE THREAD

**Issue by pajicadvance** [TonimatasDEV/PotionTimeStacker#10]
I really like this mod, but letting the player stack up effects indefinitely seems quite unbalanced. Providing a configuration option to define the maximum effect duration you can reach would be extremely useful.

Another useful addition would be an effect blacklist, as in, every effect added to this list cannot stack its effect duration.

**Comment by TonimatasDEV** [comment]
Will be added when I have free time

**Comment by TonimatasDEV** [comment]
@pajicadvance Added in the version 1.2.0

**Comment by pajicadvance** [comment]
Thanks!
