### ISSUE TITLE
Startup crash on fabric, version 1.20.1

### ISSUE THREAD

**Issue by gas-station-sushi** [TonimatasDEV/PotionTimeStacker#7]
Log: https://mclo.gs/vRN0hGn

**Comment by TonimatasDEV** [comment]
> Log: https://mclo.gs/vRN0hGn

Server or client?

**Comment by gas-station-sushi** [comment]
> > Log: https://mclo.gs/vRN0hGn
> 
> Server or client?

singleplayer client

**Comment by TonimatasDEV** [comment]
> > > Log: https://mclo.gs/vRN0hGn
> > 
> > 
> > Server or client?
> 
> singleplayer client

I fixed it some time ago, don't worry
